# Generated by Django 5.2.1 on 2025-05-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
