# Generated by Django 5.2.1 on 2025-06-22 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_stickynote_todolist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todolist",
            name="created_at",
        ),
        migrations.CreateModel(
            name="ToDoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("completed", models.BooleanField(default=False)),
                (
                    "todolist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tracker.todolist",
                    ),
                ),
            ],
        ),
    ]
